#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

[assembly: global::Android.Runtime.ResourceDesignerAttribute("InstallerApp_CrossPlat.Droid.Resource", IsApplication=true)]

namespace InstallerApp_CrossPlat.Droid
{
	
	
	[System.CodeDom.Compiler.GeneratedCodeAttribute("Xamarin.Android.Build.Tasks", "1.0.0.0")]
	public partial class Resource
	{
		
		static Resource()
		{
			global::Android.Runtime.ResourceIdManager.UpdateIdValues();
		}
		
		public static void UpdateIdValues()
		{
		}
		
		public partial class Attribute
		{
			
			static Attribute()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Attribute()
			{
			}
		}
		
		public partial class Color
		{
			
			// aapt resource value: 0x7f040000
			public const int clrHeaderBg = 2130968576;
			
			// aapt resource value: 0x7f040002
			public const int clrLightWhite = 2130968578;
			
			// aapt resource value: 0x7f040003
			public const int clrSplashBackground = 2130968579;
			
			// aapt resource value: 0x7f040001
			public const int clrWhite = 2130968577;
			
			static Color()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Color()
			{
			}
		}
		
		public partial class Drawable
		{
			
			// aapt resource value: 0x7f020000
			public const int backbutton128 = 2130837504;
			
			// aapt resource value: 0x7f020001
			public const int backbutton32 = 2130837505;
			
			// aapt resource value: 0x7f020002
			public const int backbutton48 = 2130837506;
			
			// aapt resource value: 0x7f020003
			public const int backbutton64 = 2130837507;
			
			// aapt resource value: 0x7f020004
			public const int Barcode128 = 2130837508;
			
			// aapt resource value: 0x7f020005
			public const int camera = 2130837509;
			
			// aapt resource value: 0x7f020006
			public const int door32 = 2130837510;
			
			// aapt resource value: 0x7f020007
			public const int fk36 = 2130837511;
			
			// aapt resource value: 0x7f020008
			public const int fk48 = 2130837512;
			
			// aapt resource value: 0x7f020009
			public const int fk72 = 2130837513;
			
			// aapt resource value: 0x7f02000a
			public const int fk96 = 2130837514;
			
			// aapt resource value: 0x7f02000b
			public const int FrendelLogo = 2130837515;
			
			// aapt resource value: 0x7f02000c
			public const int Icon = 2130837516;
			
			// aapt resource value: 0x7f02000d
			public const int imgCompleted = 2130837517;
			
			// aapt resource value: 0x7f02000e
			public const int imgCompletedTrans = 2130837518;
			
			// aapt resource value: 0x7f02000f
			public const int imgProgress = 2130837519;
			
			// aapt resource value: 0x7f020010
			public const int imgProgressTrans = 2130837520;
			
			// aapt resource value: 0x7f020011
			public const int imgSchedule = 2130837521;
			
			// aapt resource value: 0x7f020012
			public const int imgScheduleTrans = 2130837522;
			
			// aapt resource value: 0x7f020013
			public const int leftarrowbutton32 = 2130837523;
			
			// aapt resource value: 0x7f020014
			public const int leftarrowbutton64 = 2130837524;
			
			// aapt resource value: 0x7f020015
			public const int Memo128 = 2130837525;
			
			// aapt resource value: 0x7f020016
			public const int Memo256 = 2130837526;
			
			// aapt resource value: 0x7f020017
			public const int Memo32 = 2130837527;
			
			// aapt resource value: 0x7f020018
			public const int Memo48 = 2130837528;
			
			// aapt resource value: 0x7f020019
			public const int Memo64 = 2130837529;
			
			// aapt resource value: 0x7f02001a
			public const int MoneyBagUSDollar256 = 2130837530;
			
			// aapt resource value: 0x7f02001b
			public const int reload32 = 2130837531;
			
			// aapt resource value: 0x7f02001c
			public const int reload64 = 2130837532;
			
			// aapt resource value: 0x7f02001d
			public const int settings = 2130837533;
			
			// aapt resource value: 0x7f02001e
			public const int socialshare32 = 2130837534;
			
			// aapt resource value: 0x7f02001f
			public const int socialshare48 = 2130837535;
			
			// aapt resource value: 0x7f020020
			public const int socialshare64 = 2130837536;
			
			// aapt resource value: 0x7f020021
			public const int socialshare96 = 2130837537;
			
			// aapt resource value: 0x7f020022
			public const int StartJobButton = 2130837538;
			
			// aapt resource value: 0x7f020023
			public const int StartJobPressed = 2130837539;
			
			// aapt resource value: 0x7f020024
			public const int ToolBox128 = 2130837540;
			
			// aapt resource value: 0x7f020025
			public const int ToolBox256 = 2130837541;
			
			// aapt resource value: 0x7f020026
			public const int ToolBox32 = 2130837542;
			
			// aapt resource value: 0x7f020027
			public const int ToolBox48 = 2130837543;
			
			// aapt resource value: 0x7f020028
			public const int ToolBox64 = 2130837544;
			
			static Drawable()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Drawable()
			{
			}
		}
		
		public partial class Id
		{
			
			// aapt resource value: 0x7f080006
			public const int HeaderToolbar = 2131230726;
			
			// aapt resource value: 0x7f080000
			public const int Image = 2131230720;
			
			// aapt resource value: 0x7f080001
			public const int Text = 2131230721;
			
			// aapt resource value: 0x7f080008
			public const int imgViewIcon = 2131230728;
			
			// aapt resource value: 0x7f080007
			public const int imgbtnBack = 2131230727;
			
			// aapt resource value: 0x7f08000f
			public const int imgbtnJobs = 2131230735;
			
			// aapt resource value: 0x7f08001b
			public const int imgbtnLogOut = 2131230747;
			
			// aapt resource value: 0x7f080010
			public const int imgbtnMessages = 2131230736;
			
			// aapt resource value: 0x7f080015
			public const int imgbtnPayments = 2131230741;
			
			// aapt resource value: 0x7f080016
			public const int imgbtnSettings = 2131230742;
			
			// aapt resource value: 0x7f08000c
			public const int linearLayout1 = 2131230732;
			
			// aapt resource value: 0x7f08000e
			public const int linearLayout2 = 2131230734;
			
			// aapt resource value: 0x7f080011
			public const int linearLayout3 = 2131230737;
			
			// aapt resource value: 0x7f080014
			public const int linearLayout4 = 2131230740;
			
			// aapt resource value: 0x7f080017
			public const int linearLayout5 = 2131230743;
			
			// aapt resource value: 0x7f08001a
			public const int linearLayout6 = 2131230746;
			
			// aapt resource value: 0x7f08001c
			public const int linearLayout7 = 2131230748;
			
			// aapt resource value: 0x7f08000b
			public const int lstInstallerInfo = 2131230731;
			
			// aapt resource value: 0x7f08000a
			public const int main_content = 2131230730;
			
			// aapt resource value: 0x7f08001e
			public const int menu_reload32 = 2131230750;
			
			// aapt resource value: 0x7f080012
			public const int textView1 = 2131230738;
			
			// aapt resource value: 0x7f080013
			public const int textView2 = 2131230739;
			
			// aapt resource value: 0x7f080018
			public const int textView3 = 2131230744;
			
			// aapt resource value: 0x7f080019
			public const int textView4 = 2131230745;
			
			// aapt resource value: 0x7f08001d
			public const int textView5 = 2131230749;
			
			// aapt resource value: 0x7f080009
			public const int textViewGeneral = 2131230729;
			
			// aapt resource value: 0x7f080003
			public const int txtCompany = 2131230723;
			
			// aapt resource value: 0x7f08000d
			public const int txtInstallerName = 2131230733;
			
			// aapt resource value: 0x7f080002
			public const int txtJobNo = 2131230722;
			
			// aapt resource value: 0x7f080005
			public const int txtLot = 2131230725;
			
			// aapt resource value: 0x7f080004
			public const int txtProject = 2131230724;
			
			static Id()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Id()
			{
			}
		}
		
		public partial class Layout
		{
			
			// aapt resource value: 0x7f030000
			public const int CustomJobScreen = 2130903040;
			
			// aapt resource value: 0x7f030001
			public const int HeaderToolbar = 2130903041;
			
			// aapt resource value: 0x7f030002
			public const int JobScreen = 2130903042;
			
			// aapt resource value: 0x7f030003
			public const int Main = 2130903043;
			
			static Layout()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Layout()
			{
			}
		}
		
		public partial class Menu
		{
			
			// aapt resource value: 0x7f070000
			public const int JobMenu = 2131165184;
			
			static Menu()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Menu()
			{
			}
		}
		
		public partial class String
		{
			
			// aapt resource value: 0x7f050001
			public const int ApplicationName = 2131034113;
			
			// aapt resource value: 0x7f050000
			public const int Hello = 2131034112;
			
			static String()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private String()
			{
			}
		}
		
		public partial class Style
		{
			
			// aapt resource value: 0x7f060000
			public const int MyTheme = 2131099648;
			
			// aapt resource value: 0x7f060001
			public const int MyTheme_Splash = 2131099649;
			
			static Style()
			{
				global::Android.Runtime.ResourceIdManager.UpdateIdValues();
			}
			
			private Style()
			{
			}
		}
	}
}
#pragma warning restore 1591
